-- Maak games database aan (wordt alleen uitgevoerd bij eerste init)
CREATE DATABASE IF NOT EXISTS games CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Geef rechten aan curiodevbox gebruiker
GRANT ALL PRIVILEGES ON games.* TO 'curiodevbox'@'%';
FLUSH PRIVILEGES;

USE games;

-- Maak games tabel
CREATE TABLE IF NOT EXISTS games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    developer VARCHAR(255) NOT NULL,
    publisher VARCHAR(255),
    release_year INT,
    genre VARCHAR(100),
    platform VARCHAR(100),
    price DECIMAL(10, 2),
    description TEXT,
    rating DECIMAL(3, 1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Voeg 100 games toe
INSERT INTO games (title, developer, publisher, release_year, genre, platform, price, description, rating) VALUES
('The Witcher 3: Wild Hunt', 'CD Projekt Red', 'CD Projekt', 2015, 'RPG', 'PC, PlayStation, Xbox', 39.99, 'Een epische open-world RPG met een meeslepend verhaal en prachtige graphics.', 9.7),
('Red Dead Redemption 2', 'Rockstar Games', 'Rockstar Games', 2018, 'Action-Adventure', 'PC, PlayStation, Xbox', 59.99, 'Een western avontuur in het Amerika van 1899.', 9.8),
('The Legend of Zelda: Breath of the Wild', 'Nintendo', 'Nintendo', 2017, 'Action-Adventure', 'Nintendo Switch', 59.99, 'Een open-world avontuur in Hyrule.', 9.5),
('God of War', 'Santa Monica Studio', 'Sony Interactive', 2018, 'Action-Adventure', 'PlayStation', 49.99, 'Kratos en zijn zoon op een epische reis door de Noorse mythologie.', 9.6),
('Elden Ring', 'FromSoftware', 'Bandai Namco', 2022, 'Action RPG', 'PC, PlayStation, Xbox', 59.99, 'Een uitgestrekt open-world action RPG met moeilijke gevechten.', 9.5),
('Cyberpunk 2077', 'CD Projekt Red', 'CD Projekt', 2020, 'RPG', 'PC, PlayStation, Xbox', 49.99, 'Een cyberpunk RPG in Night City.', 8.2),
('Grand Theft Auto V', 'Rockstar North', 'Rockstar Games', 2013, 'Action-Adventure', 'PC, PlayStation, Xbox', 29.99, 'Drie verhalen verweven in Los Santos.', 9.5),
('Minecraft', 'Mojang Studios', 'Microsoft', 2011, 'Sandbox', 'Alle platforms', 26.95, 'Bouw en verken in een blokkerige wereld.', 9.0),
('Fortnite', 'Epic Games', 'Epic Games', 2017, 'Battle Royale', 'Alle platforms', 0.00, 'Gratis battle royale game.', 8.5),
('Call of Duty: Modern Warfare', 'Infinity Ward', 'Activision', 2019, 'First-Person Shooter', 'PC, PlayStation, Xbox', 59.99, 'Intensieve moderne oorlogsvoering.', 8.7),
('FIFA 23', 'EA Sports', 'Electronic Arts', 2022, 'Sports', 'PC, PlayStation, Xbox', 69.99, 'De nieuwste voetbalsimulatie.', 8.0),
('Assassin\'s Creed Valhalla', 'Ubisoft Montreal', 'Ubisoft', 2020, 'Action-Adventure', 'PC, PlayStation, Xbox', 59.99, 'Viking avonturen in Engeland.', 8.5),
('Spider-Man', 'Insomniac Games', 'Sony Interactive', 2018, 'Action-Adventure', 'PlayStation', 39.99, 'Zwaai door New York als Spider-Man.', 9.2),
('Horizon Zero Dawn', 'Guerrilla Games', 'Sony Interactive', 2017, 'Action RPG', 'PC, PlayStation', 19.99, 'Jacht op robotdinosaurussen in een post-apocalyptische wereld.', 9.0),
('The Last of Us Part II', 'Naughty Dog', 'Sony Interactive', 2020, 'Action-Adventure', 'PlayStation', 39.99, 'Een emotioneel verhaal over wraak en verlies.', 9.0),
('Super Mario Odyssey', 'Nintendo', 'Nintendo', 2017, 'Platform', 'Nintendo Switch', 59.99, 'Mario\'s 3D platform avontuur.', 9.7),
('Animal Crossing: New Horizons', 'Nintendo', 'Nintendo', 2020, 'Simulation', 'Nintendo Switch', 59.99, 'Bouw je eigen eilandparadijs.', 8.8),
('Among Us', 'InnerSloth', 'InnerSloth', 2018, 'Party', 'Alle platforms', 4.99, 'Vind de bedrieger onder je crew.', 8.0),
('Valorant', 'Riot Games', 'Riot Games', 2020, 'First-Person Shooter', 'PC', 0.00, 'Tactische FPS met unieke agenten.', 8.5),
('League of Legends', 'Riot Games', 'Riot Games', 2009, 'MOBA', 'PC', 0.00, 'De populairste MOBA ter wereld.', 8.7),
('Counter-Strike: Global Offensive', 'Valve', 'Valve', 2012, 'First-Person Shooter', 'PC', 0.00, 'Competitieve tactische shooter.', 9.0),
('Overwatch 2', 'Blizzard Entertainment', 'Blizzard', 2022, 'First-Person Shooter', 'PC, PlayStation, Xbox, Switch', 0.00, 'Team-gebaseerde hero shooter.', 7.5),
('World of Warcraft', 'Blizzard Entertainment', 'Blizzard', 2004, 'MMORPG', 'PC', 14.99, 'De legendarische MMORPG.', 8.5),
('Final Fantasy VII Remake', 'Square Enix', 'Square Enix', 2020, 'RPG', 'PC, PlayStation', 69.99, 'Hervertelling van het klassieke RPG.', 9.0),
('Persona 5 Royal', 'Atlus', 'Sega', 2020, 'RPG', 'PC, PlayStation, Switch, Xbox', 59.99, 'Stylish JRPG met unieke gameplay.', 9.5),
('Hades', 'Supergiant Games', 'Supergiant Games', 2020, 'Roguelike', 'Alle platforms', 24.99, 'Roguelike actie in de onderwereld.', 9.5),
('Celeste', 'Maddy Makes Games', 'Maddy Makes Games', 2018, 'Platform', 'Alle platforms', 19.99, 'Uitdagend platformspel met diep verhaal.', 9.0),
('Hollow Knight', 'Team Cherry', 'Team Cherry', 2017, 'Metroidvania', 'Alle platforms', 14.99, 'Atmosferische Metroidvania.', 9.4),
('Stardew Valley', 'ConcernedApe', 'ConcernedApe', 2016, 'Simulation', 'Alle platforms', 14.99, 'Rustige boerderij simulatie.', 9.5),
('Terraria', 'Re-Logic', 'Re-Logic', 2011, 'Sandbox', 'Alle platforms', 9.99, '2D sandbox avontuur.', 9.0),
('Rocket League', 'Psyonix', 'Epic Games', 2015, 'Sports', 'Alle platforms', 0.00, 'Voetbal met auto\'s.', 9.0),
('Apex Legends', 'Respawn Entertainment', 'Electronic Arts', 2019, 'Battle Royale', 'Alle platforms', 0.00, 'Battle royale met unieke legendes.', 8.5),
('Genshin Impact', 'miHoYo', 'miHoYo', 2020, 'Action RPG', 'Alle platforms', 0.00, 'Open-world gacha RPG.', 8.5),
('Dark Souls III', 'FromSoftware', 'Bandai Namco', 2016, 'Action RPG', 'PC, PlayStation, Xbox', 59.99, 'Uitdagende actie RPG.', 9.0),
('Sekiro: Shadows Die Twice', 'FromSoftware', 'Activision', 2019, 'Action-Adventure', 'PC, PlayStation, Xbox', 59.99, 'Intensieve samurai actie.', 9.5),
('Bloodborne', 'FromSoftware', 'Sony Interactive', 2015, 'Action RPG', 'PlayStation', 19.99, 'Gothic horror actie RPG.', 9.1),
('Ghost of Tsushima', 'Sucker Punch', 'Sony Interactive', 2020, 'Action-Adventure', 'PlayStation, PC', 59.99, 'Samurai avontuur in het oude Japan.', 9.3),
('Death Stranding', 'Kojima Productions', 'Sony Interactive', 2019, 'Action', 'PC, PlayStation', 59.99, 'Uniek post-apocalyptisch avontuur.', 8.5),
('Resident Evil 4', 'Capcom', 'Capcom', 2023, 'Survival Horror', 'Alle platforms', 59.99, 'Remake van het klassieke horror spel.', 9.5),
('Resident Evil Village', 'Capcom', 'Capcom', 2021, 'Survival Horror', 'Alle platforms', 59.99, 'Horror avontuur in een mysterieus dorp.', 8.5),
('The Elder Scrolls V: Skyrim', 'Bethesda', 'Bethesda', 2011, 'RPG', 'Alle platforms', 39.99, 'Open-world fantasy RPG.', 9.5),
('Fallout 4', 'Bethesda', 'Bethesda', 2015, 'RPG', 'PC, PlayStation, Xbox', 29.99, 'Post-apocalyptisch RPG.', 8.5),
('Doom Eternal', 'id Software', 'Bethesda', 2020, 'First-Person Shooter', 'Alle platforms', 59.99, 'Intensieve demon-slaying actie.', 9.0),
('Half-Life: Alyx', 'Valve', 'Valve', 2020, 'First-Person Shooter', 'PC VR', 59.99, 'Revolutionaire VR shooter.', 9.5),
('Portal 2', 'Valve', 'Valve', 2011, 'Puzzle', 'PC, PlayStation, Xbox', 9.99, 'Geniale puzzel game.', 9.5),
('The Stanley Parable', 'Galactic Cafe', 'Galactic Cafe', 2013, 'Adventure', 'PC', 14.99, 'Unieke narratieve ervaring.', 9.0),
('Disco Elysium', 'ZA/UM', 'ZA/UM', 2019, 'RPG', 'Alle platforms', 39.99, 'Detective RPG zonder gevechten.', 9.5),
('Baldur\'s Gate 3', 'Larian Studios', 'Larian Studios', 2023, 'RPG', 'PC, PlayStation, Xbox', 59.99, 'Diepe D&D gebaseerde RPG.', 9.8),
('Divinity: Original Sin 2', 'Larian Studios', 'Larian Studios', 2017, 'RPG', 'Alle platforms', 44.99, 'Tactische RPG met veel vrijheid.', 9.6),
('Mass Effect Legendary Edition', 'BioWare', 'Electronic Arts', 2021, 'RPG', 'PC, PlayStation, Xbox', 59.99, 'Remaster van de legendarische trilogie.', 9.0),
('Dragon Age: Inquisition', 'BioWare', 'Electronic Arts', 2014, 'RPG', 'PC, PlayStation, Xbox', 29.99, 'Epische fantasy RPG.', 8.5),
('The Outer Worlds', 'Obsidian Entertainment', 'Private Division', 2019, 'RPG', 'Alle platforms', 59.99, 'Space RPG met keuzes.', 8.5),
('Star Wars Jedi: Fallen Order', 'Respawn Entertainment', 'Electronic Arts', 2019, 'Action-Adventure', 'Alle platforms', 59.99, 'Star Wars avontuur met lightsaber gevechten.', 9.0),
('Star Wars Jedi: Survivor', 'Respawn Entertainment', 'Electronic Arts', 2023, 'Action-Adventure', 'PC, PlayStation, Xbox', 69.99, 'Vervolg op Fallen Order.', 9.0),
('Marvel\'s Spider-Man: Miles Morales', 'Insomniac Games', 'Sony Interactive', 2020, 'Action-Adventure', 'PlayStation, PC', 49.99, 'Spider-Man avontuur met Miles.', 8.5),
('Batman: Arkham Knight', 'Rocksteady Studios', 'Warner Bros', 2015, 'Action-Adventure', 'PC, PlayStation, Xbox', 19.99, 'Finale in de Arkham serie.', 9.0),
('Injustice 2', 'NetherRealm Studios', 'Warner Bros', 2017, 'Fighting', 'PC, PlayStation, Xbox', 19.99, 'DC vechtspel.', 8.5),
('Mortal Kombat 11', 'NetherRealm Studios', 'Warner Bros', 2019, 'Fighting', 'Alle platforms', 49.99, 'Brutale vechtspel.', 8.5),
('Street Fighter 6', 'Capcom', 'Capcom', 2023, 'Fighting', 'PC, PlayStation, Xbox', 59.99, 'Nieuwste in de Street Fighter serie.', 9.0),
('Tekken 7', 'Bandai Namco', 'Bandai Namco', 2017, 'Fighting', 'PC, PlayStation, Xbox', 19.99, '3D vechtspel.', 8.5),
('Super Smash Bros. Ultimate', 'Bandai Namco', 'Nintendo', 2018, 'Fighting', 'Nintendo Switch', 59.99, 'Ultieme crossover vechtspel.', 9.5),
('Mario Kart 8 Deluxe', 'Nintendo', 'Nintendo', 2017, 'Racing', 'Nintendo Switch', 59.99, 'Klassieke kart racing.', 9.5),
('Forza Horizon 5', 'Playground Games', 'Microsoft', 2021, 'Racing', 'PC, Xbox', 59.99, 'Open-world racing in Mexico.', 9.2),
('Gran Turismo 7', 'Polyphony Digital', 'Sony Interactive', 2022, 'Racing', 'PlayStation', 69.99, 'Realistische racing simulatie.', 8.5),
('F1 23', 'Codemasters', 'Electronic Arts', 2023, 'Racing', 'PC, PlayStation, Xbox', 69.99, 'Officiële F1 simulatie.', 8.0),
('Need for Speed Heat', 'Ghost Games', 'Electronic Arts', 2019, 'Racing', 'PC, PlayStation, Xbox', 39.99, 'Street racing avontuur.', 7.5),
('Cities: Skylines', 'Colossal Order', 'Paradox Interactive', 2015, 'Simulation', 'Alle platforms', 29.99, 'Stadsbouw simulatie.', 9.0),
('The Sims 4', 'Maxis', 'Electronic Arts', 2014, 'Simulation', 'PC, PlayStation, Xbox', 0.00, 'Levenssimulatie.', 7.5),
('Planet Zoo', 'Frontier Developments', 'Frontier Developments', 2019, 'Simulation', 'PC', 44.99, 'Dierentuin management.', 8.5),
('Crusader Kings III', 'Paradox Development Studio', 'Paradox Interactive', 2020, 'Strategy', 'PC', 49.99, 'Middeleeuwse dynastie simulator.', 9.0),
('Civilization VI', 'Firaxis Games', '2K Games', 2016, 'Strategy', 'Alle platforms', 59.99, 'Turn-based strategy.', 9.0),
('Total War: Warhammer III', 'Creative Assembly', 'Sega', 2022, 'Strategy', 'PC', 59.99, 'Epische fantasy strategy.', 8.5),
('XCOM 2', 'Firaxis Games', '2K Games', 2016, 'Strategy', 'PC, PlayStation, Xbox, Switch', 49.99, 'Tactische turn-based strategy.', 9.0),
('Fire Emblem: Three Houses', 'Intelligent Systems', 'Nintendo', 2019, 'Strategy', 'Nintendo Switch', 59.99, 'Tactische RPG met sociale elementen.', 9.5),
('Age of Empires IV', 'Relic Entertainment', 'Xbox Game Studios', 2021, 'Strategy', 'PC', 59.99, 'Real-time strategy.', 8.5),
('StarCraft II', 'Blizzard Entertainment', 'Blizzard', 2010, 'Strategy', 'PC', 0.00, 'Competitieve RTS.', 9.0),
('Hearthstone', 'Blizzard Entertainment', 'Blizzard', 2014, 'Card Game', 'PC, Mobile', 0.00, 'Strategisch kaartspel.', 8.5),
('Magic: The Gathering Arena', 'Wizards of the Coast', 'Wizards of the Coast', 2018, 'Card Game', 'PC, Mobile', 0.00, 'Digitale versie van MTG.', 8.0),
('Gwent: The Witcher Card Game', 'CD Projekt Red', 'CD Projekt', 2018, 'Card Game', 'PC, PlayStation, Xbox, Mobile', 0.00, 'Strategisch kaartspel uit The Witcher.', 8.5),
('Slay the Spire', 'MegaCrit', 'Humble Bundle', 2019, 'Roguelike', 'Alle platforms', 24.99, 'Roguelike deckbuilder.', 9.0),
('Monster Hunter: World', 'Capcom', 'Capcom', 2018, 'Action RPG', 'PC, PlayStation, Xbox', 29.99, 'Jacht op gigantische monsters.', 9.0),
('Monster Hunter Rise', 'Capcom', 'Capcom', 2021, 'Action RPG', 'PC, Switch, PlayStation, Xbox', 59.99, 'Portable monster hunting.', 9.0),
('Nioh 2', 'Team Ninja', 'Sony Interactive', 2020, 'Action RPG', 'PC, PlayStation', 59.99, 'Souls-like in het oude Japan.', 9.0),
('Nier: Automata', 'PlatinumGames', 'Square Enix', 2017, 'Action RPG', 'PC, PlayStation, Xbox, Switch', 39.99, 'Filosofische action RPG.', 9.0),
('Bayonetta 3', 'PlatinumGames', 'Nintendo', 2022, 'Action', 'Nintendo Switch', 59.99, 'Stylish actie game.', 9.0),
('Devil May Cry 5', 'Capcom', 'Capcom', 2019, 'Action', 'PC, PlayStation, Xbox', 39.99, 'Stylish demon slaying.', 9.0),
('Metal Gear Solid V', 'Kojima Productions', 'Konami', 2015, 'Action-Adventure', 'PC, PlayStation, Xbox', 19.99, 'Open-world stealth actie.', 9.0),
('Hitman 3', 'IO Interactive', 'IO Interactive', 2021, 'Stealth', 'PC, PlayStation, Xbox, Switch', 59.99, 'Stealth assassinatie game.', 9.0),
('Dishonored 2', 'Arkane Studios', 'Bethesda', 2016, 'Stealth', 'PC, PlayStation, Xbox', 29.99, 'Stealth actie met superkrachten.', 9.0),
('Prey', 'Arkane Studios', 'Bethesda', 2017, 'First-Person Shooter', 'PC, PlayStation, Xbox', 29.99, 'Sci-fi horror shooter.', 8.5),
('BioShock Infinite', 'Irrational Games', '2K Games', 2013, 'First-Person Shooter', 'PC, PlayStation, Xbox', 19.99, 'Atmosferische shooter.', 9.5),
('Borderlands 3', 'Gearbox Software', '2K Games', 2019, 'First-Person Shooter', 'Alle platforms', 59.99, 'Looter shooter met humor.', 8.5),
('Destiny 2', 'Bungie', 'Bungie', 2017, 'First-Person Shooter', 'Alle platforms', 0.00, 'Online multiplayer shooter.', 8.5),
('Warframe', 'Digital Extremes', 'Digital Extremes', 2013, 'Third-Person Shooter', 'Alle platforms', 0.00, 'Free-to-play space ninja shooter.', 8.5),
('Genshin Impact', 'miHoYo', 'miHoYo', 2020, 'Action RPG', 'Alle platforms', 0.00, 'Open-world gacha RPG.', 8.5),
('Honkai: Star Rail', 'miHoYo', 'miHoYo', 2023, 'RPG', 'PC, Mobile', 0.00, 'Turn-based space RPG.', 8.5),
('Gravity Rush 2', 'SIE Japan Studio', 'Sony Interactive', 2017, 'Action-Adventure', 'PlayStation', 19.99, 'Unieke zwaartekracht gameplay.', 8.5),
('Ratchet & Clank: Rift Apart', 'Insomniac Games', 'Sony Interactive', 2021, 'Action-Adventure', 'PlayStation, PC', 69.99, 'Dimension-hopping avontuur.', 9.0),
('Returnal', 'Housemarque', 'Sony Interactive', 2021, 'Roguelike', 'PlayStation, PC', 69.99, 'Roguelike third-person shooter.', 9.0),
('Demon\'s Souls', 'Bluepoint Games', 'Sony Interactive', 2020, 'Action RPG', 'PlayStation', 69.99, 'Remake van het originele Souls spel.', 9.0),
('Astro\'s Playroom', 'SIE Japan Studio', 'Sony Interactive', 2020, 'Platform', 'PlayStation', 0.00, 'Gratis showcase voor PS5.', 9.0),
('Kirby and the Forgotten Land', 'HAL Laboratory', 'Nintendo', 2022, 'Platform', 'Nintendo Switch', 59.99, '3D Kirby avontuur.', 9.0),
('Metroid Dread', 'MercurySteam', 'Nintendo', 2021, 'Metroidvania', 'Nintendo Switch', 59.99, '2D Metroid terugkeer.', 9.0),
('Splatoon 3', 'Nintendo', 'Nintendo', 2022, 'Third-Person Shooter', 'Nintendo Switch', 59.99, 'Team-gebaseerde ink shooter.', 8.5),
('Xenoblade Chronicles 3', 'Monolith Soft', 'Nintendo', 2022, 'RPG', 'Nintendo Switch', 59.99, 'Epische JRPG.', 9.0),
('Triangle Strategy', 'Square Enix', 'Square Enix', 2022, 'Strategy RPG', 'PC, Switch', 59.99, 'Tactische RPG met keuzes.', 8.5),
('Octopath Traveler II', 'Square Enix', 'Square Enix', 2023, 'RPG', 'PC, PlayStation, Switch', 59.99, 'HD-2D RPG met 8 verhalen.', 9.0),
('Sea of Stars', 'Sabotage Studio', 'Sabotage Studio', 2023, 'RPG', 'Alle platforms', 34.99, 'Retro-stijl RPG.', 9.0),
('Chained Echoes', 'Matthias Linda', 'Deck13', 2022, 'RPG', 'Alle platforms', 24.99, 'Indie RPG met moderne gameplay.', 9.0);

